### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'false'

### ISSUE THREAD

**Issue by velvet1976** [streamondemand/plugin.video.streamondemand#319]
From my Kodi log trail I've found this issue:

    16:02:15.047 T:1720710048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                Error Type: <type 'exceptions.ValueError'>
                                                Error Contents: invalid literal for int() with base 10: 'false'
                                                Traceback (most recent call last):
                                                  File "/storage/.kodi/addons/plugin.video.streamondemand/library_service.py", line 431, in <module>
                                                    **if config.get_setting("adult_mode") == False or config.get_setting("adult_mode") == 2:**
                                                  File "/storage/.kodi/addons/plugin.video.streamondemand/core/config.py", line 220, in get_setting
                                                    value = int(value)
                                                  ValueError: invalid literal for int() with base 10: 'false'
                                                -->End of Python script error report<--
    16:02:16.189 T:1501557664   ERROR: Traceback (most recent call last):
    16:02:16.189 T:1501557664   ERROR:   File "/storage/.kodi/addons/script.tvguide/source.py", line 346, in _updateChannelAndProgramListCaches
    16:02:16.264 T:1501557664   ERROR:     for item in self.source.getDataFromExternal(date, progress_callback):
    16:02:16.265 T:1501557664   ERROR: TypeError: 'NoneType' object is not iterable
    16:02:16.265 T:1501557664   ERROR:   File "/storage/.kodi/addons/script.tvguide/source.py", line 818, in getDataFromExternal
    16:02:16.265 T:1501557664   ERROR:     for idx, channel in enumerate(channels):

Running

    16:01:34.267 T:1962004480  NOTICE: Starting Kodi (17.3 Git:147cec4). Platform: Linux ARM 32-bit  
    16:01:34.267 T:1962004480  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)

**Comment by velvet1976** [comment]
More details about the environment.
Running on Raspberry PI 3 with plugin version 5.5.8:

    16:01:34.267 T:1962004480  NOTICE: Starting Kodi (17.3 Git:147cec4). Platform: Linux ARM 32-bit
    16:01:34.267 T:1962004480  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
    16:01:34.267 T:1962004480  NOTICE: Kodi compiled May 25 2017 by GCC 6.2.0 for Linux ARM 32-bit version 4.9.29 (264477)
    16:01:34.267 T:1962004480  NOTICE: Running on LibreELEC (official) - Version: 8.0.2, kernel: Linux ARM 32-bit version 4.9.29
    
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <addon id="plugin.video.streamondemand"
           name="Stream On Demand"
           version="5.5.8"
           provider-name="iSOD Crew">
      <requires>
        <import addon="xbmc.python" version="2.1.0"/>
        <import addon="script.module.libtorrent" optional="true"/>
      </requires>
      <extension point="xbmc.python.pluginsource" library="default.py">
        <provides>video</provides>
      </extension>
        <extension point="xbmc.addon.metadata">
            <summary lang="it">SOD Media</summary>
            <description lang="it">SOD Media</description>
            <summary lang="en">SOD Media</summary>
            <description lang="en">SOD Media</description>
            <platform>all</platform>
            <license>GNU GPL v3</license>
            <forum>http://www.mimediacenter.info/foro/viewforum.php?f=36</forum>
            <source>https://github.com/streamondemand/plugin.video.streamondemand</source>
        </extension>
        <extension point="xbmc.service" library="library_service.py" start="login|startup">
        </extension>
    </addon>
