### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by M0Rf30** [streamondemand/plugin.video.streamondemand#330]
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'false'
                                            Traceback (most recent call last):
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/library_service.py", line 431, in <module>
                                                if config.get_setting("adult_mode") == False or config.get_setting("adult_mode") == 2:
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/core/config.py", line 220, in get_setting
                                                value = int(value)
                                            ValueError: invalid literal for int() with base 10: 'false'
                                            -->End of Python script error report<--
12:12:35.930 T:140036729169664   ERROR: Previous line repeats 1 times.
12:12:35.930 T:140036729169664   ERROR: ######## ERROR #########
12:12:35.930 T:140036729169664   ERROR:     [streamondemand.core.servertools.get_server_parameters] Error al cargar el servidor: version
                                            Traceback (most recent call last):
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 495, in get_server_parameters
                                                JSONFile =  xml2dict(os.path.join(config.get_runtime_path(),"servers", server + ".xml"))["server"]
                                            KeyError: 'server'
12:12:35.938 T:140036729169664   ERROR: Exception in thread Thread-187:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 234, in update_server
                                                remote_server_url, remote_version_url = servertools.get_server_remote_url(server_name)
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 812, in get_server_remote_url
                                                remote_server_url = server_parameters["update_url"] + server_name + ".py"
                                            KeyError: 'update_url'
12:12:36.594 T:140036687206144   ERROR: ######## ERROR #########
12:12:36.594 T:140036687206144   ERROR:     [streamondemand.core.servertools.get_server_parameters] Error al cargar el servidor: version
                                            Traceback (most recent call last):
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 495, in get_server_parameters
                                                JSONFile =  xml2dict(os.path.join(config.get_runtime_path(),"servers", server + ".xml"))["server"]
                                            KeyError: 'server'
12:12:36.595 T:140036687206144   ERROR: Exception in thread Thread-187:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                                self.__target(*self.__args, **self.__kwargs)
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 234, in update_server
                                                remote_server_url, remote_version_url = servertools.get_server_remote_url(server_name)
                                              File "/home/morfeo/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 812, in get_server_remote_url
                                                remote_server_url = server_parameters["update_url"] + server_name + ".py"
                                            KeyError: 'update_url'
```

**Comment by SiNaPsEr0x** [comment]
your ram?

**Comment by M0Rf30** [comment]
8GB DDR4

**Comment by DjDiabolik** [comment]
l'errore XML2DICT l'avevo segnalato pure io su osmc che gira su un Pi2...........

Dopo averlo installato l'errore persiste................ solo quello nel mio caso.

**Comment by MrPuazzo** [comment]
per sistemare l'errore relativo ad "adult_mode" bisogna:
1) chiudere KODI
2) aprire il file  SETTINGS.XML che in windows si trova in C:\Users\[nomeutente]\AppData\Roaming\Kodi\addons\plugin.video.streamondemand\resources\
3) cercare "adult_aux_intro_password" dovreste trovarlo alla riga n. 18; quindi modificare la riga e le successive in questo modo:

`        <setting id="adult_aux_intro_password" type="text" label="Password:" option="hidden"  default="" visible="true"/>
        <setting id="adult_mode" **type="bool"** values="Mai|Sempre|Solo fino al riavvio Kodi" label="30002" enable="!eq(-1,)" default="0" visible="true"/>
        <setting id="adult_request_password" type="bool" label="Richiedi password per aprire canali per adulti"  enable="!eq(-1,0)+!eq(-2,)" default="true"visible="true"/>
        <setting id="adult_aux_new_password1" type="text" label="Nuova password:" option="hidden" enable="!eq(-3,)" default="" visible="true"/>
        <setting id="adult_aux_new_password2" type="text" label="Conferma nuova password:" option="hidden" enable="!eq(-1,)" default="" visible="true"/>
`

**Comment by DjDiabolik** [comment]
mmmmmm interessante.
Ma poi effettivamente ce ne sono di canali ? Io nel mio caso non posso chiudere kodi se non fare la modifica e sperare che la cosa diventi effettiva al successivo riavvio del Pi2.

Ma a mio avviso se hanno tolto le 3 righe possibile che non siano + necessarie ad oggi ?

**Comment by costaplus** [comment]
mi spiace deludervi e non ci sperate, non esistono canali xxx in sod! quindi modificarli è superfluo.

**Comment by DjDiabolik** [comment]
Immaginavo..........
