### ISSUE TITLE
Eccezione kodi 17.03 raspbian 8 -  plugin.video.streamondemand-v5.5.9: 

### ISSUE THREAD

**Issue by tmontanaro** [streamondemand/plugin.video.streamondemand#344]
Quando apro kodi, il sistema mi dice he streamondemand ha generato un'eccezione! Vi copio di seguito quello che trovo nel log.
Ho riscontrato il problema solo su
- kodi 17.3 installato su Raspbian GNU/Linux 8 (jessie) (Raspberry pi3)

```
22:21:03.477 T:1743008688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.ValueError'>
    Error Contents: invalid literal for int() with base 10: 'false'
    Traceback (most recent call last):
      File "/home/pi/.kodi/addons/plugin.video.streamondemand/library_service.py", line 431, in <module>
        if config.get_setting("adult_mode") == False or config.get_setting("adult_mode") == 2:
      File "/home/pi/.kodi/addons/plugin.video.streamondemand/core/config.py", line 220, in get_setting
        value = int(value)
    ValueError: invalid literal for int() with base 10: 'false'
    -->End of Python script error report<--
22:21:17.433 T:1859118000   ERROR: GetDirectory - Error getting
22:21:18.452 T:1507849136   ERROR: Previous line repeats 2 times.
22:21:18.452 T:1507849136   ERROR: ######## ERROR #########
22:21:18.452 T:1507849136   ERROR:     [streamondemand.core.servertools.get_server_parameters] Error al cargar el servidor: version
    Traceback (most recent call last):
      File "/home/pi/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 495, in get_server_parameters
        JSONFile =  xml2dict(os.path.join(config.get_runtime_path(),"servers", server + ".xml"))["server"]
    KeyError: 'server'
22:21:18.464 T:1507849136   ERROR: Exception in thread Thread-248:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/pi/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 234, in update_server
        remote_server_url, remote_version_url = servertools.get_server_remote_url(server_name)
      File "/home/pi/.kodi/addons/plugin.video.streamondemand/core/servertools.py", line 812, in get_server_remote_url
        remote_server_url = server_parameters["update_url"] + server_name + ".py"
    KeyError: 'update_url'
22:22:00.694 T:1743008688   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.ValueError'>
    Error Contents: invalid literal for int() with base 10: 'false'
    Traceback (most recent call last):
      File "/home/pi/.kodi/addons/plugin.video.streamondemand/library_service.py", line 412, in <module>
        if config.get_setting("adult_mode") == False or config.get_setting("adult_mode") == 2:
      File "/home/pi/.kodi/addons/plugin.video.streamondemand/core/config.py", line 220, in get_setting
        value = int(value)
    ValueError: invalid literal for int() with base 10: 'false'
    -->End of Python script error report<--
22:23:14.167 T:1946243744   ERROR: Previous line repeats 2 times.
```

**Comment by DjDiabolik** [comment]
Da totale ignorante ma può essere che vada in errore sulla gestione dei multi processi.............. sembra.

Nelle righe in basso vedo che c'è un get_setting "Adult_mode"... l'adult mode non mi pare sia + presente..... prova a fare un'installazione pulita oppure dalla impostazioni avanzate dell'addons se non sbaglio ci sono diversi comandi per resettare le sue impostazioni magari e solo li il problema.......

**Comment by costaplus** [comment]
Per il problema resettare user-data e tutto ritorna come prima!

**Comment by DjDiabolik** [comment]
Ma tutta la cartella userdata o solo quella relativa al SOD ?
Nel mio caso ad esempio questa -> /home/osmc/.kodi/userdata/addon_data/plugin.video.streamondemand/
