### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by iz8mbw** [streamondemand/plugin.video.streamondemand#58]
Ciao ragazzi,
non se vi può essere utile ma ho trovato questi errori nel log.

`20:52:34 T:544923971808   ERROR: Exception in thread Thread-26:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 204, in updatechannel
                                                local_version = int(matches[0])
                                            IndexError: list index out of range
20:52:34 T:544890417376   ERROR: Exception in thread Thread-30:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 204, in updatechannel
                                                local_version = int(matches[0])
                                            IndexError: list index out of range
20:52:34 T:545033023712   ERROR: Exception in thread Thread-35:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 204, in updatechannel
                                                local_version = int(matches[0])
                                            IndexError: list index out of range
20:52:34 T:544915583200   ERROR: Exception in thread Thread-42:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 204, in updatechannel
                                                local_version = int(matches[0])
                                            IndexError: list index out of range
20:52:35 T:544949137632   ERROR: Exception in thread Thread-61:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/plugin.video.streamondemand/core/updater.py", line 204, in updatechannel
                                                local_version = int(matches[0])
                                            IndexError: list index out of range
`

Eseguo l'addon su Odroid C2 su LibreELEC v7.90.008 - Kody 17 beta 5.

**Comment by dentaku65** [comment]
http://www.mimediacenter.info/foro/viewtopic.php?f=36&t=7803

**Comment by iz8mbw** [comment]
Grazie per il link ma...
1. LibreELEC installato da zero su Odroid C-2 (ARM 64bit)
2. streamondemand 5.4.1 installato da zero
3. DNS 8.8.8.8 e 8.8.4.4 impostati
4. Buffer impostato a 50MB
5. "Wait for Network" abilitato
di cos'altro hai bisogno?
