### ISSUE TITLE
Problema canale download

### ISSUE THREAD

**Issue by matteopic** [streamondemand/plugin.video.streamondemand#69]
Con una installazione pulita di Kodi e del plugin stream ondemand se si va nella cartella "Downloads" appare una finestra di errore.
Questo accade perché mancano alcune cartelle all'interno di `userdata/addon_data/plugin.video.streamondemand`.

Creando le seguenti cartelle manualmente ho risolto il problema

- downloads
- downloads/list
- downloads/list/error

**Comment by dentaku65** [comment]
sarebbero serviti i log dell'errore...

**Comment by matteopic** [comment]
Sono riuscito a ricreare parzialmente il problema, questo è parte del log  

```
19:53:54 T:4495396864  NOTICE: streamondemand.default init...
19:53:54 T:4495396864  NOTICE: streamondemand.platformcode.launcher run
19:53:54 T:4495396864  NOTICE: streamondemand.platformcode.launcher action=[errores], category=[], channel=[descargas], context=[], fanart=[/Users/matteo/Library/Application Support/Kodi/addons/plugin.video.streamondemand/fanart.jpg], fulltitle=[download con errori], infoLabels=[{}], isPlayable=[false], title=[download con errori], totalItems=[2]
19:53:54 T:4495396864  NOTICE: streamondemand.platformcode.launcher channel_file=/Users/matteo/Library/Application Support/Kodi/addons/plugin.video.streamondemand/channels/descargas.py
19:53:54 T:4495396864  NOTICE: streamondemand.platformcode.launcher running channel channels.descargas /Users/matteo/Library/Application Support/Kodi/addons/plugin.video.streamondemand/channels/descargas.pyo
19:53:54 T:4495396864  NOTICE: streamondemand.platformcode.launcher executing channel 'errores' method
19:53:54 T:4495396864  NOTICE: [descargas.py] errores
19:53:54 T:4495396864  NOTICE: ######## ERROR #########
19:53:54 T:4495396864  NOTICE:     [launcher.run] streamondemand.platformcode.launcher Traceback (most recent call last):
                                              File "/Users/matteo/Library/Application Support/Kodi/addons/plugin.video.streamondemand/platformcode/launcher.py", line 282, in run
                                                itemlist = getattr(channel, item.action)(item)
                                              File "/Users/matteo/Library/Application Support/Kodi/addons/plugin.video.streamondemand/channels/descargas.py", line 160, in errores
                                                ficheros = os.listdir(ERROR_PATH)
                                            OSError: [Errno 2] No such file or directory: '/Users/matteo/Library/Application Support/Kodi/userdata/addon_data/plugin.video.streamondemand/downloads/list/error'

```

**Comment by dentaku65** [comment]
grazie, effettivamente manca la creazione di <path>/error

**Comment by matteopic** [comment]
Ho corretto parte del codice, ora all'avvio vengono create le cartelle necessarie.
Ho creato anche una pull request.

**Comment by dentaku65** [comment]
Grazie teo! Fatto il merge
